In this project, you are going to work on the "Restaurant revenue" dataset which contains 100 observations of restaurants with 8 attributes.

**Problem Statement:**

Create a machine learning model to predict revenue of the restaurant based on the features present in the dataset.

**Dataset Attributes:**

1. **ID** - Restaurant ID
2. **Name** - Name of the Restaurant
3. **Franchise** - Restaurant has franchise or not
4. **Category** - specific type of category provided by restaurant
5. **No_of_item** - Different types of items provided by restaurant
6. **Order_Placed** - Order placed by customer to restaurant (in lacs)
7.** Revenue** - Total amount of income generated by the restaurant

**Tasks To Be Performed:**

In this project, you have to predict the restaurant revenue based on the independent features using a machine learning algorithm of your own choice.

In [2]:
#Import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [3]:
# Load dataset
df = pd.read_csv('Revenue_prediction.csv')

In [11]:
df.head()

,Id,Name,City,No_Of_Item,Order_Placed,Revenue,Franchise_No,Franchise_Yes,Category_Asian,Category_Asian/Noodle,...,Category_Healthy,Category_Italian/Pizza,Category_Mexican,Category_Pizza,Category_Sandwich,Category_Seafood,Category_Snack,Category_Sports Bar,Category_Steak,Category_Varied Menu
0,101,HungryHowie'sPizza,Bengaluru,55,5.5,5953753,0,1,0,0,...,0,0,1,0,0,0,0,0,0,0
1,102,CharleysPhillySteaks,Gurugram,72,6.8,7223131,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,103,Chuy's,Pune,25,1.9,2555379,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,104,O'Charley's,Mumbai,18,2.5,2175511,0,1,0,0,...,0,1,0,0,0,0,0,0,0,0
4,105,PolloTropical,Noida,48,4.2,4816715,0,1,0,0,...,0,0,0,1,0,0,0,0,0,0

In [14]:
df.columns

Index(['Id', 'Name', 'City', 'No_Of_Item', 'Order_Placed', 'Revenue',
       'Franchise_No', 'Franchise_Yes', 'Category_Asian',
       'Category_Asian/Noodle', 'Category_BBQ', 'Category_Bakery Cafe',
       'Category_Burger', 'Category_Chicken', 'Category_Coffee Cafe',
       'Category_Family Casual', 'Category_Family Style',
       'Category_Frozen Desserts', 'Category_Healthy',
       'Category_Italian/Pizza', 'Category_Mexican', 'Category_Pizza',
       'Category_Sandwich', 'Category_Seafood', 'Category_Snack',
       'Category_Sports Bar', 'Category_Steak', 'Category_Varied Menu'],
      dtype='object')

In [12]:
#Examining missing values
df.isnull().sum()

Id                          0
Name                        0
City                        0
No_Of_Item                  0
Order_Placed                0
Revenue                     0
Franchise_No                0
Franchise_Yes               0
Category_Asian              0
Category_Asian/Noodle       0
Category_BBQ                0
Category_Bakery Cafe        0
Category_Burger             0
Category_Chicken            0
Category_Coffee Cafe        0
Category_Family Casual      0
Category_Family Style       0
Category_Frozen Desserts    0
Category_Healthy            0
Category_Italian/Pizza      0
Category_Mexican            0
Category_Pizza              0
Category_Sandwich           0
Category_Seafood            0
Category_Snack              0
Category_Sports Bar         0
Category_Steak              0
Category_Varied Menu        0
dtype: int64

In [21]:
df = pd.get_dummies(df, columns=['City'])

In [22]:
# Define features and target
features = df.drop(columns=['Id', 'Name', 'Revenue'])
target = df['Revenue']

In [23]:
# Split dataset into training and testing
x_train, x_test, y_train, y_test = train_test_split(features, target, test_size=0.2)

In [24]:
# Define model
model = LinearRegression()

In [25]:
# Train model
model.fit(x_train, y_train)

LinearRegression()

In [26]:
# Make predictions
y_pred = model.predict(x_test)

In [27]:
# Evaluate model
mse = mean_squared_error(y_test, y_pred)
print(f'Mean Squared Error: {mse}')

Mean Squared Error: 954988034972.6774